### ISSUE TITLE
Make profile and quotas optional for users

### ISSUE THREAD

**Issue by amarao** [AlexeySetevoi/ansible-clickhouse#13]
Hello.

Next improvement is a bit more intrusive and I'd like to discuss it beforehand.
I want to make profile and quota optional, by using default value (`clickhouse_default_user_profile=default`, and `clickhouse_default_user_quota=default`).

Moreover, I have two more ideas:

1) To make `networks`  defaulting to 0.0.0.0/0 and ::/0.
2) To use clickhouse_dbs as default for clickhouse_users_custom[user].dbs.

Is it OK or it's too daring and insecure?

My goal is to have a very small config for initial use:
```
    clickhouse_dbs:
     - name: somedatabase
    clickhouse_users_custom:
     - name: someuser
       password: somepassword
```
