### ISSUE TITLE
Can`t create distributed clickhouse cluster

### ISSUE THREAD

**Issue by patsevanton** [AlexeySetevoi/ansible-clickhouse#41]
Hello!
Can`t create distributed clickhouse cluster
1) install zookeeper cluster
inventory:
```
[zookeeper]
172.26.9.211 zookeeper_myid=1
172.26.9.212 zookeeper_myid=2
172.26.9.213 zookeeper_myid=3

[zookeeper-quorum]
host[1:3]
```
playbook
```
- hosts: zookeeper
  roles:
    - andrewrothstein.zookeeper-cluster
```
2) install clickhouse cluster
inventory:
```
[clickhouse_cluster]
172.26.9.211
172.26.9.212
172.26.9.213
```
playbook
```
- hosts: clickhouse_cluster
  become: yes
  vars:
    clickhouse_shards:
      your_shard_name:
        - { host: "172.26.9.211", port: 9000 }
        - { host: "172.26.9.212", port: 9000 }
        - { host: "172.26.9.213", port: 9000 }
    clickhouse_zookeeper_nodes:
      - { host: "172.26.9.211", port: 2181 }
      - { host: "172.26.9.212", port: 2181 }
      - { host: "172.26.9.213", port: 2181 }
  roles:
    - ansible-clickhouse
```
